import test from 'node:test';import assert from 'node:assert/strict';
import { SKILLS } from '../src/data.js';
import { assignOfficerRole, captureOfficer, createInitialState, diplomacyStatus, diplomaticTransferPrisoner, discoverFruit, equipSkill, negotiateCharacterTransfer, negotiateFruitTransfer, relationshipTier, sendAid, setDiplomacy, trainFruitMastery, trainHaki, unlockHakiTechnique } from '../src/world.js';
import { render } from '../src/view.js';

test('relationship visible tier maps hidden numeric relationship',()=>{assert.equal(relationshipTier(85),'Bonded');assert.equal(relationshipTier(0),'Neutral');assert.equal(relationshipTier(-90),'Nemesis')});
test('officer assignment changes local role state',()=>{const s=createInitialState();assert.ok(assignOfficerRole(s,'kibi_camp','logistics','nami'));assert.equal(s.strongholds.kibi_camp.officerAssignments.logistics,'nami')});
test('Haki training and advanced techniques are separate',()=>{const s=createInitialState();const before=s.officers.luffy.haki.armament.techniques.length;assert.ok(unlockHakiTechnique(s,'luffy','armament','Emission','B'));assert.equal(s.officers.luffy.haki.armament.techniques.length,before+1);assert.ok(trainHaki(s,'luffy','armament'))});
test('fruit mastery is personal and unlocks incrementally',()=>{const s=createInitialState();const before=s.officers.luffy.fruitMastery.mastery;assert.ok(trainFruitMastery(s,'luffy'));assert.ok(s.officers.luffy.fruitMastery.mastery>before);assert.equal(s.fruits.fruit_nika.awakeningPotential,'S')});
test('skill loadout enforces four normals plus ultimate slot',()=>{const s=createInitialState();assert.ok(equipSkill(s,'luffy',0,'red_hawk'));assert.equal(s.officers.luffy.skills[0],'red_hawk');assert.equal(equipSkill(s,'luffy',0,'kong_gun'),false);assert.ok(equipSkill(s,'luffy',4,'kong_gun'));assert.equal(SKILLS[s.officers.luffy.skills[4]].ultimate,true)});
test('aid and diplomatic prisoner transfer work only across non-hostile relations',()=>{const s=createInitialState();const money=s.strongholds.kibi_camp.money;assert.ok(sendAid(s,'straw_hat','kozuki','kibi_camp','amigasa',{money:100,food:100}));assert.equal(s.strongholds.kibi_camp.money,money-100);captureOfficer(s,'killer','straw_hat','kibi_camp');assert.ok(diplomaticTransferPrisoner(s,'killer','kozuki'));assert.equal(s.officers.killer.captorFaction,'kozuki')});
test('character negotiation requires trust and changes faction',()=>{const s=createInitialState();setDiplomacy(s,'straw_hat','heart','alliance');s.diplomacy[['heart','straw_hat'].sort().join('|')].trust=80;s.officers.usopp.loyalty=50;assert.ok(negotiateCharacterTransfer(s,'usopp','heart'));assert.equal(s.officers.usopp.faction,'heart')});
test('Devil Fruit negotiation transfers a discovered loose world object',()=>{const s=createInitialState();const fr=s.fruits.fruit_pero;s.officers.perospero.fruitId=null;fr.ownerId=null;fr.location='kibi_camp';fr.hidden=false;fr.discoveredBy='straw_hat';setDiplomacy(s,'straw_hat','kozuki','alliance');s.diplomacy[['kozuki','straw_hat'].sort().join('|')].trust=80;assert.ok(negotiateFruitTransfer(s,'fruit_pero','kozuki'));assert.equal(fr.discoveredBy,'kozuki');assert.equal(s.strongholds[fr.location].owner,'kozuki')});
test('render exposes roster, diplomacy, world objects and map without DOM runtime',()=>{const s=createInitialState();const html=render(s,{type:'roster'},null);assert.match(html,/130 SCENARIO CHARACTERS/);assert.match(html,/Strategic Map/);assert.match(render(s,{type:'diplomacy'},null),/Diplomacy/);assert.match(render(s,{type:'objects'},null),/Devil Fruits & Named Weapons/)});

test('production is a distinct internal-affairs action',async()=>{const {produce}=await import('../src/world.js');const s=createInitialState();const before=s.strongholds.kibi_camp.food;assert.ok(produce(s,'kibi_camp'));assert.ok(s.strongholds.kibi_camp.food>before)});
