import test from 'node:test';import assert from 'node:assert/strict';
import { CHARACTERS, DEVIL_FRUITS, ROUTES, STRONGHOLDS } from '../src/data.js';
import { captureOfficer, createArmy, createInitialState, createTransport, deserialize, diplomacyStatus, equipSkill, executePrisoner, giveFruit, killCharacter, mergeArmies, recruitPrisoner, relation, serialize, setDiplomacy, skillPerformance, splitArmy, trainCharacter } from '../src/world.js';
import { beginManualBattle, setBattleAuto, step, tickManualBattle } from '../src/simulation.js';
import { createTacticalState, issueOrder, runAutoBattle, tickTactical } from '../src/tactical.js';

test('scenario data has exact topology and 130 unique characters',()=>{assert.equal(STRONGHOLDS.length,14);assert.equal(ROUTES.length,17);assert.equal(CHARACTERS.length,130);assert.equal(new Set(CHARACTERS.map(c=>c.id)).size,130)});
test('core character invariants',()=>{const s=createInitialState();assert.equal(s.officers.kaido.martial,100);assert.equal(s.officers.big_mom.martial,99);assert.equal(s.officers.luffy.martial,92);for(const o of Object.values(s.officers)){assert.ok(o.martial>=1&&o.martial<=100);assert.ok(o.intelligence>=1&&o.intelligence<=100);assert.ok(o.politics>=1&&o.politics<=100);assert.ok(o.charisma>=1&&o.charisma<=100);assert.equal(o.skills.length,5)}});
test('skill performance changes with user',()=>{const s=createInitialState();const a=skillPerformance(s.officers.luffy,'basic_strike'),b=skillPerformance(s.officers.nami,'basic_strike');assert.ok(a.power>b.power);assert.ok(a.cost>0)});
test('HP zero does not automatically mean death',()=>{const s=createInitialState();s.officers.zoro.hp=0;s.officers.zoro.status='incapacitated';assert.notEqual(s.officers.zoro.status,'dead');assert.equal(s.officers.zoro.deathResolved,false)});
test('death separates Devil Fruit and delayed respawn preserves fruit object',()=>{const s=createInitialState(7),fr=s.fruits.fruit_nika;assert.equal(fr.ownerId,'luffy');killCharacter(s,'luffy','kibi_camp');assert.equal(s.officers.luffy.status,'dead');assert.equal(fr.ownerId,null);assert.equal(fr.hidden,true);const due=fr.respawnAt;while(s.elapsedMinutes<=due)step(s,30);assert.equal(fr.hidden,false);fr.discoveredBy='straw_hat';assert.ok(giveFruit(s,'fruit_nika','zoro'));assert.equal(fr.ownerId,'zoro');assert.equal(s.officers.zoro.fruitId,'fruit_nika')});
test('prisoner can be recruited through relationship/charisma rules',()=>{const s=createInitialState(1);captureOfficer(s,'killer','straw_hat','kibi_camp');s.officers.killer.loyalty=10;s.officers.luffy.charisma=100;let ok=false;for(let i=0;i<10&&!ok;i++)ok=recruitPrisoner(s,'killer','luffy','straw_hat');assert.ok(ok);assert.equal(s.officers.killer.faction,'straw_hat');assert.equal(s.officers.killer.status,'available')});
test('execution is an explicit death resolution',()=>{const s=createInitialState();captureOfficer(s,'perospero','straw_hat','kibi_camp');assert.ok(executePrisoner(s,'perospero'));assert.equal(s.officers.perospero.status,'dead')});
test('diplomacy state changes are durable',()=>{const s=createInitialState();assert.equal(diplomacyStatus(s,'straw_hat','kozuki').status,'alliance');assert.ok(setDiplomacy(s,'straw_hat','beasts','truce'));assert.equal(diplomacyStatus(s,'beasts','straw_hat').status,'truce')});
test('army split and merge preserve troops',()=>{const s=createInitialState();const id=createArmy(s,{origin:'kibi_camp',destination:'ebisu',commanderId:'luffy',troops:1200,food:800});for(let i=0;i<40&&s.armies[id]?.status==='moving';i++)step(s,30);if(s.armies[id]?.status==='battle')setBattleAuto(s,Object.keys(s.battles)[0]);for(let i=0;i<10;i++)step(s,30);const a=s.armies[id];if(!a)return; a.status='waiting';a.location='kibi_camp';s.officers.luffy.location='kibi_camp';s.strongholds.kibi_camp.troops+=1200;s.strongholds.kibi_camp.food+=500;const spare=Object.values(s.officers).find(o=>o.faction==='straw_hat'&&o.status==='available'&&o.location==='kibi_camp');assert.ok(spare);const before=a.troops;const nid=splitArmy(s,id,{troops:200,food:100,commanderId:spare.id,destination:'ebisu'});assert.ok(nid);s.armies[nid].status='waiting';s.armies[nid].location='kibi_camp';s.officers[spare.id].location='kibi_camp';assert.ok(mergeArmies(s,id,nid));assert.equal(s.armies[id].troops,before)});
test('transport carries prisoners and fruit',()=>{const s=createInitialState();captureOfficer(s,'killer','straw_hat','kibi_camp');const fr=s.fruits.fruit_pero;fr.ownerId=null;fr.location='kibi_camp';fr.hidden=false;fr.discoveredBy='straw_hat';s.officers.perospero.fruitId=null;const commander=Object.values(s.officers).find(o=>o.faction==='straw_hat'&&o.status==='available'&&o.location==='kibi_camp'&&o.id!=='luffy');assert.ok(commander);const id=createTransport(s,{origin:'kibi_camp',destination:'amigasa',commanderId:commander.id,cargo:{prisoners:['killer'],devilFruits:['fruit_pero']}});assert.ok(id);for(let i=0;i<80&&s.transports[id];i++)step(s,30);assert.equal(s.officers.killer.location,'amigasa');assert.equal(s.fruits.fruit_pero.location,'amigasa')});
test('AUTO and manual tactical use same tactical state machinery',()=>{const s=createInitialState(22);const battle={attackerArmyIds:[],defenderArmyIds:[],garrisonTroops:2200,garrisonMorale:90};const aid=createArmy(s,{origin:'kibi_camp',destination:'ebisu',commanderId:'luffy',troops:1200,food:500});battle.attackerArmyIds=[aid];const t=createTacticalState(s,battle);assert.ok(Object.keys(t.units).length>=2);for(let i=0;i<300&&!t.winner;i++)tickTactical(s,t);assert.ok(t.winner);const s2=createInitialState(22),aid2=createArmy(s2,{origin:'kibi_camp',destination:'ebisu',commanderId:'luffy',troops:1200,food:500});const b2={attackerArmyIds:[aid2],defenderArmyIds:[],garrisonTroops:2200,garrisonMorale:90,tactical:null};assert.ok(runAutoBattle(s2,b2))});
test('manual battle one-at-a-time gate works in strategic battle',()=>{const s=createInitialState(3);createArmy(s,{origin:'kibi_camp',destination:'ebisu',commanderId:'luffy',troops:1800,food:600});for(let i=0;i<80&&!Object.keys(s.battles).length;i++)step(s,30);const bid=Object.keys(s.battles)[0];assert.ok(bid);assert.ok(beginManualBattle(s,bid));assert.equal(s.activeManualBattleId,bid);assert.equal(beginManualBattle(s,bid),false);for(let i=0;i<900&&s.activeManualBattleId;i++)tickManualBattle(s,.5);assert.equal(s.battles[bid].status,'resolved')});
test('training respects talent cap pipeline',()=>{const s=createInitialState();const before=s.officers.nami.intelligence;for(let i=0;i<5;i++)trainCharacter(s,'nami','intelligence');assert.ok(s.officers.nami.intelligence>=before)});
test('save/load roundtrip preserves expanded systems',()=>{const s=createInitialState();setDiplomacy(s,'straw_hat','beasts','truce');const x=deserialize(serialize(s));assert.equal(x.version,s.version);assert.equal(x.officers.luffy.haki.conqueror.grade,'A');assert.equal(x.fruits.fruit_nika.ownerId,'luffy');assert.equal(diplomacyStatus(x,'straw_hat','beasts').status,'truce')});
test('world changes autonomously over two weeks',()=>{const s=createInitialState(20260819);s.playerFaction='straw_hat';for(let i=0;i<14*48;i++)step(s,30);assert.ok(s.stats.aiOrders>20);assert.ok(s.stats.battlesResolved>0);assert.ok(s.stats.ownershipChanges>0)});

test('battle and waiting consume food while moving does not',()=>{const s=createInitialState();const id=createArmy(s,{origin:'kibi_camp',destination:'ebisu',commanderId:'luffy',troops:1000,food:500});const a=s.armies[id],movingFood=a.food;step(s,30);assert.equal(a.food,movingFood);a.status='waiting';for(let i=0;i<48;i++)step(s,30);assert.ok(a.food<movingFood)});
