import {BASE_FACILITIES,PREFS,START,FACILITIES,nameOf,coreOf} from './config.js';
import {makeRoads,chooseFacility,canBuild} from './village.js';
import {beginBattle,updateBattle} from './battle.js';
export class V3Sim{
 constructor(){this.money=25800;this.fame=620;this.townRank=2;this.townName='꽃의 도시';this.day=1;this.minute=490;this.paused=false;this.mode='village';this.currentSettlement='flower_capital';this.roads=makeRoads();this.facilities=BASE_FACILITIES.map(f=>({...f,level:1,uses:0,revenue:0}));this.prisoners=[];this.characters=Object.keys(PREFS).map(id=>({id,name:nameOf(id),core:coreOf(id),prefs:PREFS[id],x:START[id][0],y:START[id][1],state:'idle',path:[],wait:Math.random(),step:0,using:null,bubble:'',bubbleTime:0,personalMoney:2500+Math.floor(Math.random()*2500),location:'flower_capital',injury:'normal'}));this.settlements={flower_capital:{id:'flower_capital',name:'꽃의 도시',owner:'straw_hat',troops:2400,x:48,y:52,kind:'성',chars:this.characters.map(c=>c.id)},bakura:{id:'bakura',name:'바쿠라',owner:'beasts',troops:2800,x:66,y:47,kind:'마을',chars:['jack','ulti','page_one']},udon:{id:'udon',name:'우동',owner:'beasts',troops:3300,x:73,y:60,kind:'감옥도시',chars:['queen']},onigashima:{id:'onigashima',name:'오니가시마',owner:'beasts',troops:5200,x:80,y:20,kind:'요새',chars:['kaido','king']},amigasa:{id:'amigasa',name:'아미가사',owner:'kozuki',troops:1400,x:31,y:58,kind:'촌락',chars:[]},kuri:{id:'kuri',name:'쿠리',owner:'straw_hat',troops:900,x:28,y:37,kind:'촌락',chars:[]}};this.armies=[];this.encounter=null;this.battle=null;this.log=['꽃의 도시의 하루가 시작되었습니다.'];this.listeners=[];this.clock=0}
 onChange(f){this.listeners.push(f)} emit(){this.listeners.forEach(f=>f(this))} formatTime(){return`${String(Math.floor(this.minute/60)).padStart(2,'0')}:${String(this.minute%60).padStart(2,'0')}`}
 tick(dt){if(!this.paused){this.clock+=dt*3;while(this.clock>=1){this.clock--;if(++this.minute>=1440){this.minute=0;this.day++;this.onNewDay()}}this.updateCharacters(dt);this.updateArmies(dt);updateBattle(this,dt)}for(const c of this.characters){if(c.bubbleTime>0)c.bubbleTime-=dt;else c.bubble=''}}
 onNewDay(){this.fame+=Math.max(2,Math.floor(this.facilities.reduce((n,f)=>n+f.uses,0)/30));for(const p of this.prisoners)if(p.nextPersuadeDay<=this.day)p.cooldown=false}
 activeCharacters(){return this.characters.filter(c=>c.location===this.currentSettlement)} facilityAt(id){return this.facilities.find(f=>f.id===id)}
 updateCharacters(dt){for(const c of this.activeCharacters()){if(c.state==='moving'){c.step+=dt;if(c.step>=.18){c.step=0;const p=c.path.shift();if(p){c.x=p[0];c.y=p[1]}if(!c.path.length){c.state='using';c.wait=FACILITIES[this.facilityAt(c.using).type].stay}}}else if(c.state==='using'){if((c.wait-=dt)<=0)this.finishUse(c)}else if((c.wait-=dt)<=0){const n=chooseFacility(this,c);if(n){c.using=n.f.id;c.path=n.p;c.state='moving'}else c.wait=1}}}
 finishUse(c){const f=this.facilityAt(c.using),d=FACILITIES[f.type];f.uses++;if(d.fee){const paid=Math.min(c.personalMoney,d.fee+f.level*10);c.personalMoney-=paid;this.money+=paid;f.revenue+=paid}c.bubble=d.bubble;c.bubbleTime=1.5;if(f.type==='shop'&&Math.random()<.3)c.bubble='🛍️✨';if(f.type==='dojo'&&Math.random()<.25)c.bubble='⚔️!';if(f.type==='clinic')c.injury='normal';c.state='idle';c.using=null;c.wait=.7+Math.random()*1.8}
 canBuild(type,x,y){return canBuild(this,type,x,y)} build(type,x,y){if(!this.canBuild(type,x,y))return false;const cost=600+FACILITIES[type].rank*450;if(this.money<cost)return false;this.money-=cost;this.facilities.push({id:`${type}_${Date.now()}`,type,x,y,level:1,uses:0,revenue:0});this.emit();return true}
 upgradeFacility(id){const f=this.facilityAt(id);if(!f||f.level>=5||this.money<700*f.level)return false;this.money-=700*f.level;f.level++;this.emit();return true}
 rankRequirements(){const t=this.townRank+1;return{target:t,fame:t*500,facilities:t*3+3}} canRankUp(){const r=this.rankRequirements();return this.townRank<5&&this.fame>=r.fame&&this.facilities.length>=r.facilities} rankUp(){if(!this.canRankUp())return false;this.townRank++;this.emit();return true}
 dispatch(targetId,charIds,troops){const t=this.settlements[targetId],cs=this.characters.filter(c=>charIds.includes(c.id)&&c.location==='flower_capital');if(!t||!cs.length||troops<=0)return false;cs.forEach(c=>c.location='march');this.armies.push({id:`army_${Date.now()}`,from:'flower_capital',target:targetId,charIds:cs.map(c=>c.id),troops,progress:0,duration:8+Math.random()*5});this.mode='world';this.emit();return true}
 updateArmies(dt){for(const a of this.armies){if(a.done)continue;if((a.progress+=dt/a.duration)>=1){a.progress=1;a.done=true;const t=this.settlements[a.target];if(t.owner!=='straw_hat'){this.encounter={armyId:a.id,targetId:t.id};this.paused=true}else a.charIds.forEach(id=>this.characters.find(c=>c.id===id).location=t.id)}}}
 startBattle(){beginBattle(this);this.emit()} setBattleFocus(a,e){if(this.battle)this.battle.focus[a]=e} autoResolveEncounter(){beginBattle(this);while(this.battle&&!this.battle.finished)updateBattle(this,.8);this.mode='world';this.paused=false;this.emit()}
 capture(id,from){if(!this.prisoners.some(p=>p.id===id))this.prisoners.push({id,name:nameOf(id),from,loyalty:id==='king'?95:id==='queen'?76:65,cooldown:false,nextPersuadeDay:this.day})}
 persuade(id){const p=this.prisoners.find(x=>x.id===id);if(!p||p.cooldown)return{ok:false,msg:'아직 다시 회유할 수 없습니다.'};const ok=Math.random()<Math.max(.04,(100-p.loyalty)/150);p.cooldown=true;p.nextPersuadeDay=this.day+5;if(ok){this.prisoners=this.prisoners.filter(x=>x.id!==id);this.characters.push({id:p.id,name:p.name,core:coreOf(p.id),prefs:{dojo:7,tavern:4,restaurant:4},x:8,y:11,state:'idle',path:[],wait:1,step:0,using:null,bubble:'😐',bubbleTime:2,personalMoney:1800,location:'flower_capital',injury:'normal'});return{ok:true,msg:`${p.name}이(가) 합류했습니다.`}}return{ok:false,msg:`${p.name}은(는) 아직 마음을 열지 않았습니다.`}}
 returnToWorld(){this.mode='world';this.paused=false;this.emit()} returnToVillage(){this.currentSettlement='flower_capital';this.mode='village';this.paused=false;this.emit()}
}
