import { BASE_TRAVEL_MINUTES, CHARACTERS, DEFAULT_PLAYER_FACTION, DEVIL_FRUITS, FACTIONS, GAME_VERSION, GRADE_VALUE, INITIAL_DIPLOMACY, INITIAL_RELATIONSHIPS, PROFICIENCIES, ROUTES, SKILLS, STRONGHOLDS, TALENT_GRADES, WEAPONS } from './data.js';

const clone=v=>JSON.parse(JSON.stringify(v));
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const faction=id=>FACTIONS.find(f=>f.id===id);
export const characterTemplate=id=>CHARACTERS.find(c=>c.id===id);
export const neighbors=id=>ROUTES.flatMap(r=>r.a===id?[r.b]:r.b===id?[r.a]:[]);
export const pairKey=(a,b)=>[a,b].sort().join('|');
export function path(start,goal){if(start===goal)return[start];const q=[[start]],seen=new Set([start]);while(q.length){const p=q.shift(),cur=p.at(-1);for(const n of neighbors(cur)){if(seen.has(n))continue;const np=[...p,n];if(n===goal)return np;seen.add(n);q.push(np)}}return null}
export function rng(s){let x=s.rngState||1;x^=x<<13;x^=x>>>17;x^=x<<5;s.rngState=x>>>0;return s.rngState/4294967296}
export function event(s,text,type='world'){s.eventFeed.unshift({t:s.elapsedMinutes,type,text});s.eventFeed=s.eventFeed.slice(0,140)}

const initialOfficerLocation=(f,id)=>{
  const special={luffy:'kibi_camp',zoro:'kibi_camp',nami:'kibi_camp',sanji:'kibi_camp',law:'itachi_port',bepo:'itachi_port',kid:'mogura_port',killer:'mogura_port',kaido:'onigashima',king:'onigashima',queen:'udon_prison',jack:'bakura',big_mom:'big_mom_anchorage',perospero:'big_mom_anchorage',orochi:'flower_capital',momonosuke:'amigasa',kinemon:'habu_port',yamato:'onigashima'};
  return special[id]||STRONGHOLDS.find(h=>h.owner===f)?.id||STRONGHOLDS[0].id;
};

export function createInitialState(seed=1337){
  const strongholds=Object.fromEntries(STRONGHOLDS.map(h=>[h.id,{...clone(h),morale:100,prisoners:[],fruitIds:[],weaponIds:[],officerAssignments:{governor:null,recruiter:null,logistics:null}}]));
  const officers=Object.fromEntries(CHARACTERS.map(c=>[c.id,{...clone(c),status:'available',location:initialOfficerLocation(c.faction,c.id),assignedUnitId:null,hp:100,maxHp:100,energy:70+Math.round((c.intelligence+c.martial)/4),energyMax:70+Math.round((c.intelligence+c.martial)/4),trainingXp:{martial:0,intelligence:0,politics:0,charisma:0},equipment:[],fruitId:null,fruitMastery:null,unlockedSkills:[...new Set(c.skills)],relationships:{},captorFaction:null,deathResolved:false,hakiXp:{armament:0,observation:0,conqueror:0}}]));
  const fruits=Object.fromEntries(DEVIL_FRUITS.map(f=>[f.id,{...clone(f),ownerId:f.ownerId||null,location:null,hidden:false,respawnAt:null,discoveredBy:null}]));
  const weapons=Object.fromEntries(WEAPONS.map(w=>[w.id,{...clone(w),ownerId:w.ownerId||null,location:null,confiscatedBy:null}]));
  for(const fruit of Object.values(fruits)) if(fruit.ownerId&&officers[fruit.ownerId]){const o=officers[fruit.ownerId];o.fruitId=fruit.id;o.fruitMastery={proficiency:o.proficiencies.devilFruit||'NONE',mastery:Math.max(0,(GRADE_VALUE[o.proficiencies.devilFruit||'NONE']||0)*15),awakened:false,unlockedTechniques:fruit.skillTree.filter(id=>o.unlockedSkills.includes(id))};}
  for(const weapon of Object.values(weapons)) if(weapon.ownerId&&officers[weapon.ownerId]) officers[weapon.ownerId].equipment.push(weapon.id);
  const relationships={};for(const [a,b,v,tags] of INITIAL_RELATIONSHIPS)relationships[pairKey(a,b)]={value:v,tags:[...tags]};
  const diplomacy={};for(const a of FACTIONS)for(const b of FACTIONS)if(a.id<b.id)diplomacy[pairKey(a.id,b.id)]={status:'neutral',trust:50,since:0};for(const [a,b,status] of INITIAL_DIPLOMACY)diplomacy[pairKey(a,b)]={status,trust:status==='alliance'?78:status==='joint_front'?68:60,since:0};
  return {version:GAME_VERSION,seed,rngState:seed>>>0,elapsedMinutes:0,speed:1,paused:false,playerFaction:DEFAULT_PLAYER_FACTION,strongholds,officers,fruits,weapons,relationships,diplomacy,armies:{},transports:{},battles:{},activeManualBattleId:null,nextIds:{army:1,transport:1,battle:1},aiCooldownMinutes:0,eventFeed:[{t:0,type:'world',text:'Wano sandbox initialized. Canon defines the starting state only.'}],stats:{battlesResolved:0,ownershipChanges:0,aiOrders:0,prisonersTaken:0,recruits:0,diplomacyActions:0,fruitRespawns:0,manualBattles:0}};
}

export function setPlayerFaction(s,id){if(!faction(id))return false;s.playerFaction=id;event(s,`Player faction changed to ${faction(id).short}.`,'system');return true}
export const available=(s,f,loc)=>Object.values(s.officers).filter(o=>o.faction===f&&o.location===loc&&o.status==='available');
export const prisonersAt=(s,loc)=>Object.values(s.officers).filter(o=>o.status==='prisoner'&&o.location===loc);
export function command(o){if(!o)return 40;const bonus=(o.traits||[]).reduce((n,t)=>n+({'Natural Leader':8,Commander:10,'Grand Commander':16,Strategist:7,Logistician:4}[t]||0),0);return clamp(o.charisma*.46+o.martial*.22+o.intelligence*.20+o.politics*.12+bonus,1,120)}
export function travel(s,a,b){const x=s.strongholds[a],y=s.strongholds[b];return Math.round(BASE_TRAVEL_MINUTES+Math.hypot(x.x-y.x,x.y-y.y)*7)}
export function relation(s,a,b){return s.relationships[pairKey(a,b)]||{value:0,tags:[]}}
export function relationshipTier(value){return value>=80?'Bonded':value>=50?'Friendly':value>=20?'Warm':value>-20?'Neutral':value>-50?'Cold':value>-80?'Hostile':'Nemesis'}
export function changeRelation(s,a,b,delta,tag=null){const k=pairKey(a,b),r=s.relationships[k]||{value:0,tags:[]};r.value=clamp(r.value+delta,-100,100);if(tag&&!r.tags.includes(tag))r.tags.push(tag);s.relationships[k]=r;return r}
export function diplomacyStatus(s,a,b){if(a===b)return{status:'same_faction',trust:100};return s.diplomacy[pairKey(a,b)]||{status:'neutral',trust:50,since:0}}
export const isHostile=(s,a,b)=>a!==b&&!['alliance','joint_front','truce'].includes(diplomacyStatus(s,a,b).status);
export function setDiplomacy(s,a,b,status,actor=a){if(a===b||!faction(a)||!faction(b)||!['neutral','alliance','truce','joint_front','war'].includes(status))return false;const k=pairKey(a,b),d=s.diplomacy[k]||{trust:50};d.status=status;d.since=s.elapsedMinutes;d.trust=clamp(d.trust+(status==='alliance'?10:status==='joint_front'?6:status==='truce'?4:status==='war'?-25:0),0,100);s.diplomacy[k]=d;s.stats.diplomacyActions++;event(s,`${faction(actor).short} and ${faction(actor===a?b:a).short} now have ${status.replace('_',' ')} relations.`,'diplomacy');return true}
export function sendAid(s,fromFaction,toFaction,fromStronghold,toStronghold,{money=0,food=0,troops=0}={}){const h=s.strongholds[fromStronghold],t=s.strongholds[toStronghold];if(!h||!t||h.owner!==fromFaction||t.owner!==toFaction||diplomacyStatus(s,fromFaction,toFaction).status==='war')return false;money=Math.max(0,Math.floor(money/100)*100);food=Math.max(0,Math.floor(food/100)*100);troops=Math.max(0,Math.floor(troops/100)*100);if(h.money<money||h.food<food||h.troops<troops)return false;h.money-=money;h.food-=food;h.troops-=troops;t.money+=money;t.food+=food;t.troops+=troops;s.diplomacy[pairKey(fromFaction,toFaction)].trust=clamp(diplomacyStatus(s,fromFaction,toFaction).trust+6,0,100);event(s,`${faction(fromFaction).short} sent aid to ${faction(toFaction).short}.`,'diplomacy');return true}

export function develop(s,id,actor=s.playerFaction){const h=s.strongholds[id];if(!h||h.owner!==actor||h.money<300||h.development>=h.cap)return false;h.money-=300;h.development=Math.min(h.cap,h.development+3);event(s,`${h.name} development increased to ${h.development}/${h.cap}.`,'economy');return true}
export function produce(s,id,actor=s.playerFaction){const h=s.strongholds[id];if(!h||h.owner!==actor||h.money<220)return false;const manager=h.officerAssignments?.logistics?s.officers[h.officerAssignments.logistics]:null,yieldFood=Math.round(450+h.development*4+(manager?.intelligence||0)*2);h.money-=220;h.food+=yieldFood;event(s,`${h.name} completed production: +${yieldFood} food.`,'economy');return true}
export function recruit(s,id,amount=500,actor=s.playerFaction){const h=s.strongholds[id],n=Math.max(100,Math.floor(amount/100)*100),mc=Math.round(n*.7),fc=Math.round(n*.5);if(!h||h.owner!==actor||h.money<mc||h.food<fc)return false;h.money-=mc;h.food-=fc;h.troops+=n;event(s,`${h.name} recruited ${n.toLocaleString()} troops.`,'military');return true}
export function trade(s,id,kind,amount=500,actor=s.playerFaction){const h=s.strongholds[id],n=Math.max(100,Math.floor(amount/100)*100);if(!h||h.owner!==actor)return false;const rate=Math.max(.5,1.35-h.market/150);if(kind==='buy_food'){const cost=Math.round(n*rate);if(h.money<cost)return false;h.money-=cost;h.food+=n;event(s,`${h.name} bought ${n} food for ${cost} money.`,'economy');return true}if(kind==='sell_food'){if(h.food<n)return false;const gain=Math.round(n/rate*.72);h.food-=n;h.money+=gain;event(s,`${h.name} sold ${n} food for ${gain} money.`,'economy');return true}return false}
export function assignOfficerRole(s,strongholdId,role,officerId,actor=s.playerFaction){const h=s.strongholds[strongholdId],o=s.officers[officerId];if(!h||h.owner!==actor||!['governor','recruiter','logistics'].includes(role)||!o||o.faction!==actor||o.status!=='available'||o.location!==strongholdId)return false;h.officerAssignments[role]=officerId;event(s,`${o.name} assigned as ${role} at ${h.name}.`,'system');return true}

function assign(s,id,unit){const o=s.officers[id];o.status='deployed';o.assignedUnitId=unit}
export function release(s,id,loc,status='available'){const o=s.officers[id];if(!o)return;o.location=loc;o.status=status;o.assignedUnitId=null;if(status!=='prisoner')o.captorFaction=null}
export function createArmy(s,{factionId=s.playerFaction,origin,destination,commanderId,deputyId=null,troops=1000,food=500}){const h=s.strongholds[origin],c=s.officers[commanderId],d=deputyId?s.officers[deputyId]:null,p=path(origin,destination),t=Math.max(100,Math.floor(troops/100)*100),f=Math.max(0,Math.floor(food/100)*100);if(!h||h.owner!==factionId||!c||c.faction!==factionId||c.status!=='available'||c.location!==origin||!p||p.length<2||h.troops<t||h.food<f||deputyId===commanderId)return null;if(d&&(d.faction!==factionId||d.status!=='available'||d.location!==origin))return null;h.troops-=t;h.food-=f;const id=`army_${s.nextIds.army++}`;s.armies[id]={id,factionId,commanderId,deputyId,troops:t,food:f,morale:100,location:origin,destination,path:p,legIndex:0,legElapsed:0,legDuration:travel(s,p[0],p[1]),status:'moving'};assign(s,commanderId,id);if(d)assign(s,deputyId,id);event(s,`${c.name} formed an army of ${t.toLocaleString()} at ${h.name}.`,'military');return id}
export function createTransport(s,{factionId=s.playerFaction,origin,destination,commanderId,cargo={}}){const h=s.strongholds[origin],c=s.officers[commanderId],p=path(origin,destination),norm=k=>Math.max(0,Math.floor(Number(cargo[k]||0)/100)*100),load={money:norm('money'),food:norm('food'),troops:norm('troops'),prisoners:clone(cargo.prisoners||[]),devilFruits:clone(cargo.devilFruits||[])};if(!h||h.owner!==factionId||!c||c.faction!==factionId||c.status!=='available'||c.location!==origin||!p||p.length<2||h.money<load.money||h.food<load.food||h.troops<load.troops)return null;for(const pid of load.prisoners){const pz=s.officers[pid];if(!pz||pz.status!=='prisoner'||pz.location!==origin||pz.captorFaction!==factionId)return null}for(const fid of load.devilFruits){const fr=s.fruits[fid];if(!fr||fr.ownerId||fr.location!==origin||fr.hidden)return null}h.money-=load.money;h.food-=load.food;h.troops-=load.troops;for(const pid of load.prisoners)s.officers[pid].location=null;for(const fid of load.devilFruits)s.fruits[fid].location=null;const id=`transport_${s.nextIds.transport++}`;s.transports[id]={id,factionId,commanderId,cargo:load,location:origin,destination,path:p,legIndex:0,legElapsed:0,legDuration:travel(s,p[0],p[1]),status:'moving'};assign(s,commanderId,id);event(s,`${c.name} departed ${h.name} with a transport bound for ${s.strongholds[destination].name}.`,'logistics');return id}
export function moveArmy(s,id,destination){const a=s.armies[id],p=a?path(a.location,destination):null;if(!a||a.status==='battle'||!p||p.length<2)return false;Object.assign(a,{destination,path:p,legIndex:0,legElapsed:0,legDuration:travel(s,p[0],p[1]),status:'moving'});event(s,`${s.officers[a.commanderId].name}'s army is moving toward ${s.strongholds[destination].name}.`,'military');return true}
export function splitArmy(s,id,{troops,food,commanderId,deputyId=null,destination}){const a=s.armies[id];if(!a||a.status!=='waiting'||a.troops<troops+100||a.food<food||s.strongholds[a.location].owner!==a.factionId)return null;const h=s.strongholds[a.location];h.troops+=Math.floor(troops/100)*100;h.food+=Math.floor(food/100)*100;const nid=createArmy(s,{factionId:a.factionId,origin:a.location,destination,commanderId,deputyId,troops,food});if(!nid){h.troops-=Math.floor(troops/100)*100;h.food-=Math.floor(food/100)*100;return null}a.troops-=Math.floor(troops/100)*100;a.food-=Math.floor(food/100)*100;event(s,`${s.officers[a.commanderId].name}'s army split at ${h.name}.`,'military');return nid}
export function mergeArmies(s,targetId,sourceId){const a=s.armies[targetId],b=s.armies[sourceId];if(!a||!b||a.id===b.id||a.factionId!==b.factionId||a.location!==b.location||a.status!=='waiting'||b.status!=='waiting')return false;a.troops+=b.troops;a.food+=b.food;a.morale=Math.round((a.morale+b.morale)/2);release(s,b.commanderId,b.location);if(b.deputyId)release(s,b.deputyId,b.location);delete s.armies[sourceId];event(s,`Two armies merged at ${s.strongholds[a.location].name}.`,'military');return true}
export function disband(s,id){const a=s.armies[id],h=a?s.strongholds[a.location]:null;if(!a||!h||h.owner!==a.factionId||a.status!=='waiting')return false;h.troops+=a.troops;h.food+=a.food;release(s,a.commanderId,a.location);if(a.deputyId)release(s,a.deputyId,a.location);delete s.armies[id];event(s,`Army disbanded into ${h.name}'s garrison.`,'military');return true}

export function proficiencyScore(o,skill){const vals=PROFICIENCIES.map(k=>GRADE_VALUE[o.proficiencies?.[k]||'NONE']);return Math.max(...vals,0)*15}
export function hakiScore(o){return (GRADE_VALUE[o.haki.armament.grade]*7+GRADE_VALUE[o.haki.conqueror.grade]*5+GRADE_VALUE[o.haki.observation.grade]*3)}
export function skillPerformance(o,skillId){const sk=SKILLS[skillId];if(!o||!sk)return null;const scale=sk.scaling||{},prof=proficiencyScore(o,sk),haki=hakiScore(o);const value=sk.power+(o.martial||0)*(scale.martial||0)+(o.intelligence||0)*(scale.intelligence||0)+(o.charisma||0)*(scale.charisma||0)+prof*(scale.proficiency||0)+haki*(scale.haki||0);const efficiency=1+Math.max(0,prof-45)/300;return{power:Math.round(value),cost:Math.max(4,Math.round(sk.cost/efficiency)),range:sk.range,area:sk.area||0,morale:sk.morale||0,troopBias:sk.troopBias||1,moraleRestore:sk.moraleRestore||0}}
export function equipSkill(s,officerId,slot,skillId){const o=s.officers[officerId],sk=SKILLS[skillId];if(!o||!sk||!o.unlockedSkills.includes(skillId)||slot<0||slot>4)return false;if(slot===4&&!sk.ultimate)return false;if(slot<4&&sk.ultimate)return false;o.skills[slot]=skillId;return true}
export function trainCharacter(s,officerId,stat,actor=s.playerFaction){const o=s.officers[officerId];if(!o||o.faction!==actor||o.status!=='available'||!['martial','intelligence','politics','charisma'].includes(stat))return false;const h=s.strongholds[o.location];if(!h||h.owner!==actor||h.money<200)return false;h.money-=200;const grade=o.talents[stat],mult={E:.5,D:.7,C:1,B:1.3,A:1.7,S:2.2}[grade]||1,cap={E:65,D:72,C:80,B:88,A:95,S:100}[grade]||80;o.trainingXp[stat]+=25*mult;if(o.trainingXp[stat]>=100&&o[stat]<cap){o.trainingXp[stat]-=100;o[stat]++;event(s,`${o.name}'s ${stat} increased to ${o[stat]}.`,'growth')}else event(s,`${o.name} trained ${stat}.`,'growth');return true}
export function unlockHakiTechnique(s,officerId,line,technique,required='B'){const o=s.officers[officerId];if(!o?.haki?.[line]||GRADE_VALUE[o.haki[line].grade]<GRADE_VALUE[required])return false;if(!o.haki[line].techniques.includes(technique))o.haki[line].techniques.push(technique);return true}
export function trainHaki(s,officerId,line,actor=s.playerFaction){const o=s.officers[officerId];if(!o||o.faction!==actor||o.status!=='available'||!o.haki?.[line])return false;const h=s.strongholds[o.location];if(!h||h.owner!==actor||h.money<250)return false;h.money-=250;const talent=GRADE_VALUE[o.haki[line].talent]||1,current=GRADE_VALUE[o.haki[line].grade]||0;o.hakiXp[line]=(o.hakiXp[line]||0)+12+talent*4;if(o.hakiXp[line]>=100&&current<talent){o.hakiXp[line]-=100;o.haki[line].grade=['NONE','E','D','C','B','A','S'][current+1];event(s,`${o.name}'s ${line} Haki advanced to ${o.haki[line].grade}.`,'growth')}else event(s,`${o.name} trained ${line} Haki.`,'growth');return true}
export function trainFruitMastery(s,officerId,actor=s.playerFaction){const o=s.officers[officerId];if(!o||o.faction!==actor||o.status!=='available'||!o.fruitId||!o.fruitMastery)return false;const h=s.strongholds[o.location];if(!h||h.owner!==actor||h.money<250)return false;h.money-=250;o.fruitMastery.mastery=clamp(o.fruitMastery.mastery+6,0,100);if(o.fruitMastery.mastery>=30&&o.fruitMastery.proficiency==='E')o.fruitMastery.proficiency='D';if(o.fruitMastery.mastery>=50&&o.fruitMastery.proficiency==='D')o.fruitMastery.proficiency='C';if(o.fruitMastery.mastery>=65&&o.fruitMastery.proficiency==='C')o.fruitMastery.proficiency='B';if(o.fruitMastery.mastery>=80&&o.fruitMastery.proficiency==='B')o.fruitMastery.proficiency='A';if(o.fruitMastery.mastery>=95&&o.fruitMastery.proficiency==='A')o.fruitMastery.proficiency='S';if(o.fruitMastery.mastery>=100&&!o.fruitMastery.awakened&&['A','S'].includes(s.fruits[o.fruitId].awakeningPotential)){o.fruitMastery.awakened=true;event(s,`${o.name} awakened ${s.fruits[o.fruitId].name}.`,'fruit')}o.proficiencies.devilFruit=o.fruitMastery.proficiency;const fr=s.fruits[o.fruitId],idx=Math.min(fr.skillTree.length-1,Math.floor(o.fruitMastery.mastery/Math.max(1,100/fr.skillTree.length)));const sid=fr.skillTree[idx];if(sid&&!o.fruitMastery.unlockedTechniques.includes(sid)){o.fruitMastery.unlockedTechniques.push(sid);if(!o.unlockedSkills.includes(sid))o.unlockedSkills.push(sid)}event(s,`${o.name} trained ${fr.name} mastery (${o.fruitMastery.mastery}/100).`,'growth');return true}

export function captureOfficer(s,officerId,captorFaction,location){const o=s.officers[officerId];if(!o||o.status==='dead')return false;o.status='prisoner';o.location=location;o.assignedUnitId=null;o.captorFaction=captorFaction;s.stats.prisonersTaken++;event(s,`${o.name} was taken prisoner by ${faction(captorFaction).short}.`,'prisoner');return true}
export function recruitPrisoner(s,officerId,recruiterId,actor=s.playerFaction){const p=s.officers[officerId],r=s.officers[recruiterId];if(!p||p.status!=='prisoner'||p.captorFaction!==actor||!r||r.faction!==actor)return false;const rel=relation(s,p.id,r.id).value,facTrust=diplomacyStatus(s,p.faction,actor).trust,chance=clamp((100-p.loyalty)+r.charisma*.35+rel*.35+(50-facTrust)*.2,5,85);if(rng(s)*100>chance){p.loyalty=Math.max(10,p.loyalty-4);event(s,`${p.name} refused recruitment.`,'prisoner');return false}p.faction=actor;p.status='available';p.captorFaction=null;p.loyalty=58;p.location=r.location;s.stats.recruits++;changeRelation(s,p.id,r.id,15,'recruited_by');event(s,`${p.name} joined ${faction(actor).short}.`,'prisoner');return true}
export function releasePrisoner(s,officerId,actor=s.playerFaction){const p=s.officers[officerId];if(!p||p.status!=='prisoner'||p.captorFaction!==actor)return false;const home=Object.values(s.strongholds).find(h=>h.owner===p.faction);p.status='available';p.captorFaction=null;p.location=home?.id||p.location;const k=pairKey(actor,p.faction);if(s.diplomacy[k])s.diplomacy[k].trust=clamp(s.diplomacy[k].trust+8,0,100);event(s,`${p.name} was released.`,'diplomacy');return true}
export function executePrisoner(s,officerId,actor=s.playerFaction){const p=s.officers[officerId];if(!p||p.status!=='prisoner'||p.captorFaction!==actor)return false;killCharacter(s,officerId,p.location,'execution');for(const f of FACTIONS)if(f.id!==actor){const k=pairKey(actor,f.id);if(s.diplomacy[k])s.diplomacy[k].trust=clamp(s.diplomacy[k].trust-4,0,100)}event(s,`${p.name} was executed by ${faction(actor).short}.`,'death');return true}
export function exchangePrisoners(s,aId,bId,actor=s.playerFaction){const a=s.officers[aId],b=s.officers[bId];if(!a||!b||a.status!=='prisoner'||b.status!=='prisoner'||a.captorFaction!==actor||b.faction!==actor||!b.captorFaction)return false;const other=b.captorFaction;if(a.faction!==other)return false;releasePrisoner(s,aId,actor);b.status='available';b.captorFaction=null;b.location=Object.values(s.strongholds).find(h=>h.owner===actor)?.id||b.location;const k=pairKey(actor,other);if(s.diplomacy[k])s.diplomacy[k].trust=clamp(s.diplomacy[k].trust+10,0,100);event(s,`${a.name} and ${b.name} were exchanged.`,'diplomacy');return true}

export function killCharacter(s,officerId,location,reason='death'){const o=s.officers[officerId];if(!o||o.status==='dead')return false;o.status='dead';o.hp=0;o.assignedUnitId=null;o.deathResolved=true;if(o.fruitId){const fr=s.fruits[o.fruitId];if(fr){fr.ownerId=null;fr.location=location;fr.hidden=true;fr.discoveredBy=null;fr.respawnAt=s.elapsedMinutes+720+Math.floor(rng(s)*1440);s.stats.fruitRespawns++;event(s,`${fr.name} vanished after ${o.name}'s ${reason}; it may reappear near the incident region later.`,'fruit')}o.fruitId=null;o.fruitMastery=null}for(const wid of [...o.equipment]){const w=s.weapons[wid];if(w){w.ownerId=null;w.location=location}o.equipment=[]}return true}
export function discoverFruit(s,fruitId,factionId=s.playerFaction){const fr=s.fruits[fruitId];if(!fr||fr.ownerId||fr.hidden||!fr.location)return false;fr.discoveredBy=factionId;event(s,`${faction(factionId).short} discovered ${fr.name} at ${s.strongholds[fr.location].name}.`,'fruit');return true}
export function giveFruit(s,fruitId,officerId,actor=s.playerFaction){const fr=s.fruits[fruitId],o=s.officers[officerId];if(!fr||fr.ownerId||fr.hidden||fr.discoveredBy!==actor||!o||o.faction!==actor||o.status!=='available'||o.location!==fr.location||o.fruitId)return false;fr.ownerId=o.id;fr.location=null;o.fruitId=fr.id;o.fruitMastery={proficiency:'E',mastery:0,awakened:false,unlockedTechniques:fr.skillTree.slice(0,1)};o.proficiencies.devilFruit='E';for(const sid of o.fruitMastery.unlockedTechniques)if(!o.unlockedSkills.includes(sid))o.unlockedSkills.push(sid);event(s,`${o.name} ate ${fr.name}. Mastery begins from the new user's own proficiency.`,'fruit');return true}
export function equipWeapon(s,weaponId,officerId,actor=s.playerFaction){const w=s.weapons[weaponId],o=s.officers[officerId];if(!w||w.ownerId||!o||o.faction!==actor||o.status!=='available'||w.location!==o.location||o.equipment.length>=3)return false;w.ownerId=o.id;w.location=null;o.equipment.push(w.id);event(s,`${o.name} equipped ${w.name}.`,'equipment');return true}
export function confiscatePrisonerWeapons(s,officerId,actor=s.playerFaction){const o=s.officers[officerId];if(!o||o.status!=='prisoner'||o.captorFaction!==actor)return false;for(const wid of [...o.equipment]){const w=s.weapons[wid];w.ownerId=null;w.location=o.location;w.confiscatedBy=actor}o.equipment=[];event(s,`${o.name}'s named weapons were confiscated.`,'equipment');return true}

export function diplomaticTransferPrisoner(s,officerId,toFaction,actor=s.playerFaction){const p=s.officers[officerId];if(!p||p.status!=='prisoner'||p.captorFaction!==actor||!faction(toFaction)||isHostile(s,actor,toFaction))return false;const dest=Object.values(s.strongholds).find(h=>h.owner===toFaction);if(!dest)return false;p.captorFaction=toFaction;p.location=dest.id;event(s,`${p.name} was diplomatically transferred to ${faction(toFaction).short}.`,'diplomacy');return true}
export function negotiateCharacterTransfer(s,officerId,toFaction,actor=s.playerFaction){const o=s.officers[officerId];if(!o||o.faction!==actor||o.status!=='available'||!faction(toFaction)||isHostile(s,actor,toFaction)||o.loyalty>=90)return false;const dest=Object.values(s.strongholds).find(h=>h.owner===toFaction);if(!dest)return false;const trust=diplomacyStatus(s,actor,toFaction).trust;if(trust<55)return false;o.faction=toFaction;o.location=dest.id;o.loyalty=62;event(s,`${o.name} transferred from ${faction(actor).short} to ${faction(toFaction).short} by negotiation.`,'diplomacy');return true}
export function negotiateFruitTransfer(s,fruitId,toFaction,actor=s.playerFaction){const fr=s.fruits[fruitId];if(!fr||fr.ownerId||fr.hidden||fr.discoveredBy!==actor||isHostile(s,actor,toFaction)||diplomacyStatus(s,actor,toFaction).trust<55)return false;const dest=Object.values(s.strongholds).find(h=>h.owner===toFaction);if(!dest)return false;fr.location=dest.id;fr.discoveredBy=toFaction;event(s,`${fr.name} was transferred to ${faction(toFaction).short} through diplomacy.`,'diplomacy');return true}
export function worldTime(m){const d=Math.floor(m/1440)+1,x=m%1440;return`Wano Day ${d} · ${String(Math.floor(x/60)).padStart(2,'0')}:${String(x%60).padStart(2,'0')}`}
export function unitPosition(s,u){if(u.status!=='moving'){const h=s.strongholds[u.location];return h?{x:h.x,y:h.y}:{x:0,y:0}}const a=s.strongholds[u.path[u.legIndex]],b=s.strongholds[u.path[u.legIndex+1]],p=clamp(u.legElapsed/u.legDuration,0,1);return{x:a.x+(b.x-a.x)*p,y:a.y+(b.y-a.y)*p}}
export const eta=u=>u.status==='moving'?Math.max(0,Math.round(u.legDuration-u.legElapsed)):0;
export const serialize=s=>JSON.stringify(s);
export function deserialize(raw){const s=JSON.parse(raw);if(!s||s.version!==GAME_VERSION||!s.strongholds||!s.officers||!s.fruits||!s.diplomacy)throw Error('Incompatible or invalid save data.');return s}
